update from source install instructions
typst/typst pull request #130
Opened 2023-03-22 11:21 UTC by JayceFayne

2023-03-22 11:46 UTC, AntoniosBarotsis commented on README.md
> +git clone https://github.com/typst/typst
Maybe add a `--depth 1` here as there's a decent amount of commits already.

2023-03-22 11:48 UTC, AntoniosBarotsis commented
Maybe it's worth waiting for #108 so that we can add that to the readme as well.

2023-03-22 14:54 UTC, CGMossa requested changes
If I actually wanted to do this, I'd just:
```
cargo install --git https://github.com/typst/typst
```

2023-04-11 10:12 UTC, laurmaedje commented
I added something along these lines to the Readme.

2023-04-11 10:12 UTC, closed without merging